#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2023.2.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Mar 09 20:50:58 PDT 2025
# SW Build 4126759 on Thu Feb  8 23:52:05 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim divide_by_three_TB_behav -key {Behavioral:sim_1:Functional:divide_by_three_TB} -tclbatch divide_by_three_TB.tcl -view /media/ryanfeng/HardDisk/Study/Git_Repos/UVM_knowledge/divide_f_by_3/divide_by_three_TB_behav.wcfg -log simulate.log"
xsim divide_by_three_TB_behav -key {Behavioral:sim_1:Functional:divide_by_three_TB} -tclbatch divide_by_three_TB.tcl -view /media/ryanfeng/HardDisk/Study/Git_Repos/UVM_knowledge/divide_f_by_3/divide_by_three_TB_behav.wcfg -log simulate.log

