######################################################################
#
# File name : divide_by_three_TB_wave.do
# Created on: Sun Mar 09 22:25:20 PDT 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
