######################################################################
#
# File name : divide_by_three_TB_elaborate.do
# Created on: Sun Mar 09 22:25:44 PDT 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
/usr/questasim/questasim/bin/vopt -64 +acc=npr -suppress 10016 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -work xil_defaultlib xil_defaultlib.divide_by_three_TB xil_defaultlib.glbl -o divide_by_three_TB_opt
