#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2023.2.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Feb 20 11:17:25 PST 2025
# SW Build 4126759 on Thu Feb  8 23:52:05 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim four_bit_adder_TB_behav -key {Behavioral:sim_1:Functional:four_bit_adder_TB} -tclbatch four_bit_adder_TB.tcl -view /media/ryanfeng/HardDisk/Study/Git_Repos/UVM_knowledge/4bit_adder/four_bit_adder_TB_behav.wcfg -log simulate.log"
xsim four_bit_adder_TB_behav -key {Behavioral:sim_1:Functional:four_bit_adder_TB} -tclbatch four_bit_adder_TB.tcl -view /media/ryanfeng/HardDisk/Study/Git_Repos/UVM_knowledge/4bit_adder/four_bit_adder_TB_behav.wcfg -log simulate.log

